# Generated by Django 3.1.2 on 2021-03-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBR', '0002_auto_20210315_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='item_dimensions',
            field=models.CharField(choices=[('0.40', '0.40'), ('0.45', '0.45'), ('0.50', '0.50'), ('0.55', '0.55'), ('0.60', '0.60')], max_length=5, null=True),
        ),
    ]
