# Generated by Django 3.1.2 on 2021-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBR', '0003_additem_item_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='item_gaze',
            field=models.CharField(choices=[('హెవీ', 'హెవీ'), ('లైట్', 'లైట్'), ('అల్ట్రా', 'అల్ట్రా')], default='లైట్', max_length=20),
        ),
        migrations.AlterField(
            model_name='additem',
            name='item_name',
            field=models.CharField(choices=[('10mm షీట్(3x4)', '10mm షీట్(3x4)'), ('12mm షీట్(3x4)', '12mm షీట్(3x4)'), ('బాటం', 'బాటం'), ('పట్టి', 'పట్టి'), ('SPL', 'SPL'), ('Support L', 'Support L'), ('POP బ్యాగ్', 'POP బ్యాగ్'), ('మేకులు', 'మేకులు'), ('Fan Hook', 'Fan Hook'), ('Star స్క్రూలు', 'Star స్క్రూలు'), ('ఎంకర్ బోల్టులు', 'ఎంకర్ బోల్టులు')], default='10mm షీట్(3x4)', max_length=20),
        ),
    ]
