# Generated by Django 3.1.2 on 2021-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBR', '0004_auto_20210315_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='item_gaze',
            field=models.CharField(choices=[('హెవీ', 'హెవీ'), ('లైట్', 'లైట్'), ('అల్ట్రా', 'అల్ట్రా')], max_length=20, null=True),
        ),
    ]
