# Generated by Django 3.1.2 on 2021-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBR', '0005_auto_20210315_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='item_dimensions',
            field=models.CharField(blank=True, choices=[('0.40', '0.40'), ('0.45', '0.45'), ('0.50', '0.50'), ('0.55', '0.55'), ('0.60', '0.60')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='item_gaze',
            field=models.CharField(blank=True, choices=[('హెవీ', 'హెవీ'), ('లైట్', 'లైట్'), ('అల్ట్రా', 'అల్ట్రా')], max_length=20, null=True),
        ),
    ]
