# Generated by Django 3.1.2 on 2021-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBR', '0006_auto_20210315_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='item_status',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='item_dimensions',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='item_gaze',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
