# Generated by Django 3.1.2 on 2021-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBR', '0007_auto_20210315_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='item_name',
            field=models.CharField(choices=[('10mm షీట్(3x4)', '10mm షీట్(3x4)'), ('12mm షీట్(3x4)', '12mm షీట్(3x4)'), ('బాటం', 'బాటం'), ('పట్టి', 'పట్టి'), ('SPL', 'SPL'), ('సపోర్ట్ L', 'సపోర్ట్ L'), ('POP బ్యాగ్', 'POP బ్యాగ్'), ('మేకులు', 'మేకులు'), ('ఫ్యాన్ హుక్', 'ఫ్యాన్ హుక్'), ('Star స్క్రూలు', 'Star స్క్రూలు'), ('ఎంకర్ బోల్టులు', 'ఎంకర్ బోల్టులు')], default='10mm షీట్(3x4)', max_length=20),
        ),
    ]
